name: Deploy

on:
  workflow_run:
    workflows: [Build]
    types: [completed]
    branches: [main]

jobs:
  deploy-prod:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: Plan-My-Journey/PlanMyJourney-Workflows/.github/workflows/reusable-deploy.yml@main
    with:
      environment: production
      image_tag: ${{ github.event.workflow_run.head_sha }}
      overlay_path: kustomize/overlays/prod
    secrets:
      GITOPS_PAT: ${{ secrets.GITOPS_PAT }}
